name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build for David
      run: ./configure David && make

    - name: Rename for David
      run: cp chrome-filter.crx David-chrome-filter.crx

    - name: Build for Yuval
      run: ./configure Yuval && make

    - name: Rename for Yuval
      run: cp chrome-filter.crx Yuval-chrome-filter.crx

    - name: Archive artifacts for David
      uses: actions/upload-artifact@v4
      with:
        name: David-chrome-filter.crx
        path: ./David-chrome-filter.crx

    - name: Archive artifacts for Yuval
      uses: actions/upload-artifact@v4
      with:
        name: Yuval-chrome-filter.crx
        path: ./Yuval-chrome-filter.crx
